version: '3.8'

services:
  # Aplicação Next.js
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/expense_management
      - JWT_SECRET=your_super_secret_jwt_key_here
      - NEXTAUTH_URL=http://localhost:3000
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_app_password
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongo
    networks:
      - expense_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"

  # MongoDB Database
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password_123
      - MONGO_INITDB_DATABASE=expense_management
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - expense_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  # MongoDB Express (Admin Interface)
  mongo-express:
    image: mongo-express:1.0.0-alpha
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secure_password_123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secure_password_123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - expense_network
    restart: unless-stopped

  # Nginx Reverse Proxy (for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - app
    networks:
      - expense_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  mongo_data:
    driver: local

networks:
  expense_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16